name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: asia-southeast1
  SERVICE: fastfill-backend
  REGION: asia-southeast1

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker to use gcloud as credential helper
      run: |
        gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev
    - name: Build and Push Docker image
      run: |
        docker build -t $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/fastfill/$SERVICE:$GITHUB_SHA .
        docker push $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/fastfill/$SERVICE:$GITHUB_SHA
    - name: Deploy to Cloud Run
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
      run: |
        gcloud run deploy $SERVICE \
          --image $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/fastfill/$SERVICE:$GITHUB_SHA \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --port=8080 \
          --memory=4Gi \
          --cpu=8 \
          --timeout=300 \
          --max-instances=15 \
          --min-instances=2 \
          --concurrency=80 \
          --service-account=${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }} \
          --add-cloudsql-instances=${{ secrets.CLOUD_SQL_CONNECTION_NAME }} \
          --set-env-vars="DB_HOST=${DB_HOST}" \
          --set-env-vars="DB_PORT=${DB_PORT}" \
          --set-env-vars="DB_USER=${DB_USER}" \
          --set-env-vars="DB_PASSWORD=${DB_PASSWORD}" \
          --set-env-vars="DB_NAME=${DB_NAME}" \
          --set-env-vars="GCS_BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME }}" \
          --set-env-vars="GOOGLE_CLOUD_PROJECT=${PROJECT_ID}" \
          --set-env-vars="SERVER_PORT=8080" \
          --set-env-vars="ENVIRONMENT=production" \
          --set-env-vars="FRONTEND_URL_1=https://www.app.dooform.com" \
          --set-env-vars="FRONTEND_URL_2=https://www.dooform.com" \
          --set-env-vars="API_BASE_URL=${API_BASE_URL}" \
          --verbosity=debug